#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Outline
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{framed,color}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2017 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Physical Chemistry for Chemical Engineers (CHE 30324)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 1}}
#+LATEX_HEADER:\rhead{\bf{Due January 25, 2017}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Physical Chemistry for Chemical Engineers\\(CHE 30324)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage{siunitx}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS
# \begin{framed}
\noindent Each question is worth 4 points. Solutions may be provided either in hand-written form on engineering or loose leaf paper, or as a print out of a math notebook (iPython or Matlab or Mathematica). In either case, solutions should be neat and complete, answers clearly indicated, and  good plotting practice used for all plots.
# \end{framed}

* Discrete, probably
In five card stud, a poker player is dealt five cards from a standard deck of 52 cards.

1. How many different 5-card hands are there? (Remember, in poker the order the cards are received is unimportant.)

2. What is the probability of being dealt a four-of-a-kind (a card of the same rank from each suit?)

3. What is the probability of being dealt a flush (five cards of the same suit)?

* Continuous, probably
The probability distribution function for a random variable \(x\) is given by \(P(x)=x e^{-2x}, 0\le x < \infty\).

1. Is \(P(x)\) normalized? If not, normalize it.  Plot the normalized \(P(x)\).

2. What is the most probable value of \(x\)?

3. What is the expectation value of \(x\)?

4. What is the variance of \(x\)?

* One rough night
It's late on a Friday night and people are stumbling up Notre Dame Ave. to their dorms. You observe one particularly impaired individual who is taking steps of equal length \SI{1}{m} to the north or south (i.e., in one dimension), with equal probability.

1. What is the furthest distance the person could travel after 20 steps?

2. What is the probability that the person won't have traveled any net distance at all after 20 steps?

3. What is the probability that the person has traveled half the maximum distance after 20 steps?

4. Plot the probability of traveling a given distance vs distance. Does the probability distribution look familiar?  You'll see it again when we talk about diffusion.

* Now /this/ is what /I/ call equilibrium 
The Boltzmann distribution tells us that, at thermal equilibrium, the probability of a particle having an energy \(E\) is proportional to \(\exp(-E/k_\text{B}T)\), where \(k_\text{B}\) is the Boltzmann constant.  Suppose a bunch of gas particles of mass \(m\) are in thermal equilibrium at temperature \(T\) and are traveling back and forth in one dimension with various velocities \(v\) and kinetic energies \(K=mv^2/2\).
1. What is the expectation value of the velocity \(v\) of a particle?

2. What is the expectation value of the kinetic energy \(K\) of a particle? How does your answer depend on the particle mass? On temperature?
