#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CHE 30324 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
# #+LATEX_HEADER:\setlength{\headheight}{10.2pt}
# #+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2019 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Physical Chemistry for Chemical Engineers\\(CHE 30324)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage[small]{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.0\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.0\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.1\baselineskip}{0.0\baselineskip}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_EXPORT latex
\begin{center}
\textsc{\Large Physical Chemistry for Chemical Engineers (CHE 30324)}\\University of Notre Dame, Spring 2019
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
Prof.\ Bill Schneider & Classroom: 127 HH\\
Office: 180 Fitzpatrick & Lecture MWF 10:30-11:20\\
\email{wschneider@nd.edu}, phone 574-631-8754\\
\hline
\end{tabular*}
#+END_EXPORT

* Physical Chemistry
Chemical Engineers describe the macroscopic, material world around us in terms of classical models like Newton’s Laws of motion or the three Laws of Thermodynamics. Yet we know that the world is made up of femtoscopic objects, like atoms and electrons, that obey the very different rules of quantum mechanics. In this course we will learn how to use quantum mechanics to describe atoms, molecules, and their interactions with light, and how to use statistical mechanics to create a bridge between the bizarre quantum mechanical world and the familiar macroscopic one. We will learn how these two can be used to describe the physical properties of gases, liquids, and solids, and how they form the basis for understanding the mechanisms and rates of chemical reactions.

Physical chemistry is the fundamental physical basis of all Chemical Engineering. It is an exciting and lively topic, and much of the material will be new to you. I strongly encourage you to keep up with the reading and homework and to ask questions in class. Don't be bashful: if you don't understand something, chances are some of your classmates (and perhaps even your instructor!) don't either.
* (Suggested) Text
Engel and Reid, /Physical Chemistry/, Benjamin-Cummings, 2006 or 2009. Each topic will include some suggested problems from this book to give you practice with the material.
* Lecture
The topics will be presented in a series of self-contained
lectures. Attendance is expected, and you should be prepared to ask
and answer questions.  

#+CAPTION: Brief Outline of Course Topics
|--------------------------------------------+----------------|
| Probability and the Boltzmann Distribution | Chapters 29-31 |
| Physical Properties of Gases and Liquids   | Chapters 07-11 |
| Introduction to Quantum Mechanics          | Chapters 12-14 |
| Basic Applications of Quantum Mechanics    | Chapters 15-18 |
| Atomic Structure and Spectroscopy          | Chapters 19-22 |
| Molecular Structure and Spectroscopy       | Chapters 23-28 |
| Statistical Thermodynamics                 | Chapters 32-33 |
| Chemical Kinetics                          | Chapters 35-36 |
|--------------------------------------------+----------------|

* Web
This syllabus, reading assignment, the homework assignments and solutions, a summary of the lecture schedule, and a [[https://github.com/wmfschneider/CHE30324/tree/master/Outline/CHE30324-outline.pdf][detailed course outline]] are available on the web at [[https://github.com/wmfschneider/CHE30324]].  If you want to get your own copy of all this material and understand a bit about how git works, see [[http://rogerdudler.github.io/git-guide/]].  Or just download files directly from the git site. The source files are written using Org Mode ([[https://orgmode.org/]]), but you can read them using a regular text editor if you want to see under the hood.

* Homework
Eleven graded problem sets will be distributed during the semester and will be due at the beginning of class on dates to be announced.  *Assignments turned in late will automatically lose 20%, and those turned in after the solutions are posted will not be accepted.*  Your two lowest scores on homework will be dropped.  You may discuss the homework with your classmates, but *what you turn in must be your own work.*
Homework will in general require some computations. You may write out solutions by hand, being mindful that neatness counts. 

** Jupyter/Python
Alternatively, homework will also be distributed as [[https://jupyter.org/][Jupyter notebooks]] (https://jupyter.org), a powerful, open source computing notebook environment that works within a web browser. Jupyter allows one to do among other things, create and execute [[https://www.python.org/][Python]] (https:/www.python.org) programs, which are similar in syntax to Matlab. Use is optional, but if you are interested, you can download Jupyter and Python as one distribution, at [[http://anaconda.com/download]]. A tutorial on both will be provided outside of regular class hours at a time to be announced.
* Homework Defense
To help me get to know you and how you are doing with the course, after each homework assignment six of you will be chosen at random to meet with me one-on-one to discuss their homework.

* Grading
Grades will be based on homework (25%), three in-class exams (45%), and a cumulative final (30%).

* Academic honesty
Should go without saying. Any cheating or misrepresenting of work as your own will be dealt with according to the Honor Code policies of the university. I reserve the right to relocate any students during an examination at my discretion.

* Professional courtesy
As a courtesy to the instructor and your classmates, please refrain from
texting, web browsing, tweeting, chatting, updating, or using your phone or laptop for any
purpose during class time.  If you must use an electronic device, excuse
yourself from class.

* Office hours
The TA and instructor are happy to answer questions during regular office hours or by appointment if you need extra help.

| Dr. Bill Schneider | \email{wschneider@nd.edu} | By appt/drop in | 182 Fitz |
| Jerry Crum         | \email{jcrum@nd.edu}      | M 4-5           | 150 Fitz |
| Yixiao Hou         | \email{yhou@nd.edu}       | T 4-5           | 150 Fitz |
| Jian-Ren Lim       | \email{jlim6@nd.edu}      | T 4-5           | 150 Fitz |
| Craig Waitt        | \email{cwaitt@nd.edu}     | Th 4-5          | 150 Fitz |


#+CAPTION: Tentative Course Calendar
|----------+----------+-------------+-------+----------+--------------+---------------|
|          | 1/16     | 1/18        |       | 3/18     | 3/20         | 3/22          |
|          | Welcome! |             | XXXXX |          | *HW 7*       |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 1/21     | 1/23     | 1/25        |       | 3/25     | 3/27         | 3/29          |
|          | *HW 1*   |             |       |          | *HW 8*       |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 1/28     | 1/30     | 2/1         |       | 4/1      | 4/3          | 4/5           |
|          | *HW 2*   |             |       |          | *HW 9*       |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 2/4      | 2/6      | 2/8         |       | 4/8      | 4/10         | 4/12          |
|          | *HW 3*   | *Exam 1*    |       | *Exam 3* |              |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 2/11     | 2/13     | 2/15        |       | 4/15     | 4/17         | 4/19          |
|          |          | *HW 4, JPW* |       |          | *HW 10*      | *Good Friday* |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 2/19     | 2/21     | 2/23        |       | 4/22     | 4/24         | 4/26          |
|          |          | *HW 5*      |       | *Easter* |              |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 2/25     | 2/27     | 3/1         |       | 4/29     | 5/1          | 5/3           |
|          |          | *HW 6*      |       |          | *Last class* | *HW 11*       |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 3/4      | 3/6      | 3/8         |       |          | *Final Exam* |               |
| *Exam 2* |          |             |       |          | *TBD*        |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
| 3/11     | 3/13     | 3/15        |       |          |              |               |
| *BREAK*  | *BREAK*  | *BREAK*     |       |          |              |               |
|----------+----------+-------------+-------+----------+--------------+---------------|
